export const FETCH_FILM_LIST_REQUEST = "filmReducer/FETCH_FILM_LIST_REQUEST";
export const FETCH_FILM_LIST_SUCCESS = "filmReducer/FETCH_FILM_LIST_SUCCESS";
export const FETCH_FILM_LIST_FAILED = "filmReducer/FETCH_FILM_LIST_FAILED";